#!/bin/bash

set -e

VENV_DIR="env"

if [ ! -d "$VENV_DIR" ]; then
    echo "Creating virtual environment in '$VENV_DIR'"
    python3 -m venv $VENV_DIR
else
    echo "Virtual environment already exists, using '$VENV_DIR'"
fi

echo "Activating virtual environment '$VENV_DIR'"
source $VENV_DIR/bin/activate

if ! command -v maturin &> /dev/null; then
    echo "Maturin not found in '$VENV_DIR', installing..."
    pip install maturin
else
    echo "Maturin is already installed (in '$VENV_DIR'). Installed version is:"
    maturin --version
fi

STUB_COMMAND="cargo run --bin stub-gen --release"
echo "Generating stub file (.pyi) with command: '$STUB_COMMAND'"
$STUB_COMMAND

BUILD_CMD="maturin build --release --strip --sdist --target-dir target --out target/wheels"
echo "Building Python package with command: '$BUILD_CMD'"
$BUILD_CMD

echo "Build complete."
